name: BUILD PDF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Install Playwright Chromimum 
      run: npm i -D playwright-chromium
    - name: Install slidev
      run: npm i -g @slidev/cli
    - name: Run Playwright Build PDF
      run: slidev export --dark
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: .
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./presentation.pdf
