name: Playwright Build PDF
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Install Playwright Chromimum 
      run: npm i -D playwright-chromium
    - name: Install slidev
      run: npm i -g @slidev/cli
    - name: Run Playwright Build PDF
      run: slidev export --dark
      # env:
      #   # This might depend on your test-runner/language binding
      #   PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}